all:
  children:
    bastion: 
      hosts:
        bastion1:  
          ansible_host: 18.199.97.197
          ansible_user: ubuntu
          ansible_port: 22
          ansible_python_interpreter: /usr/bin/python3

    k8s_cluster:
      children:
        kube_control_plane:
          hosts:
            master1:
              ansible_host: 10.0.2.112
              ansible_user: ubuntu
              ansible_python_interpreter: /usr/bin/python3
        kube_node:
          hosts:
            worker1:
              ansible_host: 10.0.3.43
              ansible_user: ubuntu
              ansible_python_interpreter: /usr/bin/python3
            worker2:
              ansible_host: 10.0.3.5
              ansible_user: ubuntu
              ansible_python_interpreter: /usr/bin/python3

        etcd:
          hosts:
            master1:
              ansible_python_interpreter: /usr/bin/python3
        calico_rr:
          hosts: {}
