apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  type: NodePort
  selector:
    app: app1
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 3001 #  порт для доступа извне
