apiVersion: metallb.io/v1beta1
kind: IPAddressPool #пул ip адресов для их назначения сервисам 
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.49.200-192.168.49.250 
