---
apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: app1-data-pool
  namespace: rook-ceph
spec:
  failureDomain: host #данные будут реплицированы по различным хостам в кластере - отказоустойчивость

---

apiVersion: ceph.rook.io/v1
kind: CephBlockPool
metadata:
  name: metadata-pool
  namespace: rook-ceph
spec:
  failureDomain: host

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-ceph-storage-class
  namespace: rook-ceph
provisioner: ceph.rook.io/block #провайдер для динамического выделения хранилища — Rook Ceph
parameters:
  blockPool: app1-data-pool #пул для хранения данных самого приложения- app1
  dataPool: metadata-pool #пул(логическая группа) для хранения метаданных
  reclaimPolicy: Delete #когда PVC удаляется, PV также будет удален
---

apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  cephVersion:
    image: ceph/ceph:v17.2.0
  dataDirHostPath: /var/lib/rook
  storage:
    useAllNodes: true
    useAllDevices: true
  network:
    provider: host # Ceph будет управлять репликацией данных на уровне хостов, но в этой версии не дает он 
    #указать репликацию пулов, так что оставлю на будущее на всякий(если буду менять версию)
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app1-pvc
  namespace: default #где и приложение 
spec:
  accessModes:
    - ReadWriteMany #позволяет нескольким подам одновременно монтировать один и тот же PV-блоч ус-во (rwx)
    #ceph его поддерж + у меня же 2 пода с приложением 
    #!!! данные находятся в ceph, но доступ к ним через pv которые нах в подах app1
  resources:
    requests:
      storage: 3Gi  #даже если 2 пода с приложением -то все равно 1 физ PV c 3 гб
  storageClassName: rook-ceph-storage-class


  #output kubectl apply -f ceph.yaml
#cephblockpool.ceph.rook.io/app1-data-pool unchanged
#cephblockpool.ceph.rook.io/metadata-pool unchanged
#storageclass.storage.k8s.io/rook-ceph-storage-class unchanged
#cephcluster.ceph.rook.io/rook-ceph-cluster unchanged
#persistentvolumeclaim/app1-pvc unchanged

